import Head from 'next/head';

// Components
import { NavBar, Footer, Content } from '../components';

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Content />
        <Footer />
      </main>
    </>
  );
};

export default Home;
